plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-3.2.0.cjs

# Fixes `this makes the require call ambiguous and unsound` error, when dependency tries to import peer dependency.
packageExtensions:
  '@lerna-lite/core@*':
    dependencies:
      'pify': '*'